name: Deploy GitHub Release Assets

on:
  workflow_call:
    secrets:
      TOKEN_TO_UPLOAD_ASSETS:
        required: true

jobs:
  deploy_github_release_assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: deliverables
          path: ./

      - run: ls -l

      - uses: svenstaro/upload-release-action@6b7fa9f267e90b50a19fef07b3596790bb941741 # 2.11.3
        with:
          repo_token: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}
          file_glob: true
          file: ./*.deb
      - uses: svenstaro/upload-release-action@6b7fa9f267e90b50a19fef07b3596790bb941741 # 2.11.3
        with:
          repo_token: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}
          file_glob: true
          file: ./*.deb.sha256sum
      - uses: svenstaro/upload-release-action@6b7fa9f267e90b50a19fef07b3596790bb941741 # 2.11.3
        with:
          repo_token: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}
          file_glob: true
          file: ./*.deb.sha512sum
