name: Deploy GitHub Release Assets

on:
  workflow_call:
    secrets:
      TOKEN_TO_UPLOAD_ASSETS:
        required: true

jobs:
  deploy_github_release_assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: deliverables
          path: ./
      - run: ls -l
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}
          file_glob: true
          file: ./*.deb
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}
          file_glob: true
          file: ./*.deb.sha256sum
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}
          file_glob: true
          file: ./*.deb.sha512sum
